/** Theme option UI string keys (RU field names without _en suffix). */
export const UI_STRING_KEYS = [
  'footer_disclaimer',
  'footer_cookie_notice',
  'footer_copyright',
  'contact_popup_title',
  'contact_popup_text',
  'header_portfolio_label',
  'header_portfolio_aria',
  'header_about_label',
  'header_about_aria',
  'header_home_aria',
  'drawer_open_aria',
  'drawer_close_aria',
  'drawer_menu_aria',
  'case_nav_see_also',
  'case_nav_prev_label',
  'case_nav_next_label',
  'case_nav_none',
  'portfolio_heading_current',
  'portfolio_heading_legacy',
  'portfolio_link_current',
  'portfolio_archive_description',
  'seo_hidden_h1',
  'lang_switch_aria',
  'hero_order_label',
  'hero_portfolio_label',
  'hero_logo_alt',
  'services_section_heading',
  'services_price_from',
  'services_heading_archive',
  'services_archive_description',
  'services_back_to_archive',
  'case_thanks_message',
  'case_back_to_portfolio',
  'case_mobile_signature_default_heading',
  'case_mobile_signature_default_text',
  'case_content_default_heading',
  'case_content_default_text',
  'screenshot_lightbox_dialog_label',
  'screenshot_lightbox_close_aria',
  'screenshot_lightbox_toggle_aria',
  'nav_verb_click',
  'nav_verb_tap',
  'hud_menu_open',
  'hud_menu_close',
  'hud_nav_mark',
  'hud_mobile_close',
  'hud_sys_meta',
  'hud_node_idle',
  'hud_node_format',
  'hud_status_node_idle',
  'hud_status_node_format',
  'hud_status_idle',
  'hud_status_ready',
  'hud_status_active',
  'chrome_index_kicker',
  'chrome_case_label',
  'chrome_service_label',
  'case_section_overview',
  'case_section_interface',
  'case_section_mobile',
  'case_section_slices',
] as const;

export type UiStringKey = (typeof UI_STRING_KEYS)[number];

export type UiStrings = Record<UiStringKey, string | null>;
